import type { NextPage } from 'next'
import Head from 'next/head'
import styled from '@emotion/styled'
import { useState } from 'react'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>후레임</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledTetrisWrapper role="button" tabIndex={0}>
        <StyledTetris>Start Here!</StyledTetris>

        <Copyright>
          <a
            href="https://kr.freepik.com/free-vector/deep-forest-with-sunny-glade-green-grass-and-tree-trunks-silhouettes-vector-cartoon-illustration-of-summer-woods-landscape-with-sunshine-beams-jungle-panorama-with-green-lawn_24025354.htm#query=game%20background&position=3&from_view=keyword"
            target="new"
          >
            작가 upklyak
          </a>
          &nbsp; 출처 Freepik
        </Copyright>

        <Image
          src="/background.jpg"
          layout="fill"
          objectFit="cover"
          objectPosition="center"
          alt="background"
          priority
          style={{ zIndex: '0' }}
        />
      </StyledTetrisWrapper>
    </div>
  )
}

export const StyledTetrisWrapper = styled.div`
  width: 100%;
  height: 100vh;
  overflow: hidden;
  outline: none;
  background-color: #dfdfbd;
  position: relative;
`

export const StyledTetris = styled.div`
  z-index: 2;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px;
  margin: 0 auto;
  .display {
    display: flex;
    justify-content: space-between;
    width: 380px;
  }
`

export const Copyright = styled.p`
  z-index: 2;
  font-size: 1.2rem;
  position: absolute;
  bottom: 0;
  right: 10px;
  color: #e2e2e2;

  &:hover {
    color: #c2c2c2;
  }
`

export default Home
